spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/itcast_health?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
mybatis:
  type-aliases-package: com.itheima.pojo

